export const depositrequestData = [
  {
    user_id: 'U001',
    amount: 5000,
    status: 'Pending',
    comment: 'Initial deposit request',
    admin_comment: 'Reviewed and pending approval',
    bank: 'Bank of America',
    'date/Time': '2024-08-10 08:00:00',
  },
  {
    user_id: 'U002',
    amount: 15000,
    status: 'Approved',
    comment: 'Urgent deposit for trading',
    admin_comment: 'Approved on 2024-08-11',
    bank: 'Chase Bank',
    'date/Time': '2024-08-10 09:15:00',
  },
  {
    user_id: 'U003',
    amount: 7500,
    status: 'Rejected',
    comment: 'Deposit amount exceeds limit',
    admin_comment: 'Rejected due to policy violation',
    bank: 'Wells Fargo',
    'date/Time': '2024-08-10 10:30:00',
  },
  {
    user_id: 'U004',
    amount: 2000,
    status: 'Pending',
    comment: 'Standard deposit request',
    admin_comment: 'Under review',
    bank: 'Citibank',
    'date/Time': '2024-08-10 11:45:00',
  },
  {
    user_id: 'U005',
    amount: 10000,
    status: 'Approved',
    comment: 'Large deposit for investment',
    admin_comment: 'Approved and processed',
    bank: 'HSBC',
    'date/Time': '2024-08-10 13:00:00',
  },
  {
    user_id: 'U006',
    amount: 3000,
    status: 'Pending',
    comment: 'Deposit for account funding',
    admin_comment: 'Awaiting further verification',
    bank: 'Barclays',
    'date/Time': '2024-08-10 14:15:00',
  },
  {
    user_id: 'U007',
    amount: 12000,
    status: 'Approved',
    comment: 'High-value deposit request',
    admin_comment: 'Approved after confirmation',
    bank: 'Deutsche Bank',
    'date/Time': '2024-08-10 15:30:00',
  },
  {
    user_id: 'U008',
    amount: 5000,
    status: 'Rejected',
    comment: 'Deposit rejected due to invalid account',
    admin_comment: 'Rejected and notified user',
    bank: 'UBS',
    'date/Time': '2024-08-10 16:45:00',
  },
  {
    user_id: 'U009',
    amount: 8000,
    status: 'Pending',
    comment: 'Request for partial deposit',
    admin_comment: 'Pending user verification',
    bank: 'Standard Chartered',
    'date/Time': '2024-08-10 18:00:00',
  },
  {
    user_id: 'U010',
    amount: 2200,
    status: 'Approved',
    comment: 'Deposit for new account setup',
    admin_comment: 'Processed successfully',
    bank: 'Goldman Sachs',
    'date/Time': '2024-08-10 19:15:00',
  },
  {
    user_id: 'U011',
    amount: 1000,
    status: 'Rejected',
    comment: 'Deposit amount too low',
    admin_comment: 'Rejected due to minimum deposit requirement',
    bank: 'Morgan Stanley',
    'date/Time': '2024-08-10 20:30:00',
  },
];
