export const columns = [
    { header: 'ID', accessor: 'id' },
    { header: 'Account', accessor: 'account' },
    { header: 'Amount', accessor: 'amount' },
    { header: 'Comment', accessor: 'comment' },
    { header: 'Admin Comment', accessor: 'adminComment' },
    { header: 'Branch', accessor: 'branch' },
    { header: 'Date/Time', accessor: 'dateTime' },
    { header: 'Action', accessor: 'action' },
];


export const data = [
    {
        id: 'TXN12345',
        account: 'JohnDoe123',
        amount: '$1,200.00',
        comment: 'Pending withdrawal',
        adminComment: 'Reviewed',
        branch: 'NY',
        dateTime: '2024-08-10 12:45 PM',
    },
    {
        id: 'TXN12346',
        account: 'JaneSmith456',
        amount: '$3,400.00',
        comment: 'Pending approval',
        adminComment: 'Requires further verification',
        branch: 'LA',
        dateTime: '2024-08-10 01:15 PM',
    },
    {
        id: 'TXN12347',
        account: 'AliceGreen789',
        amount: '$2,100.00',
        comment: 'Pending processing',
        adminComment: 'Verified',
        branch: 'SF',
        dateTime: '2024-08-10 02:00 PM',
    },
    {
        id: 'TXN12348',
        account: 'MichaelBrown101',
        amount: '$750.00',
        comment: 'Withdrawal approved',
        adminComment: 'Processed',
        branch: 'TX',
        dateTime: '2024-08-10 03:30 PM',
    },
    {
        id: 'TXN12349',
        account: 'EmilyDavis202',
        amount: '$900.00',
        comment: 'Pending approval',
        adminComment: 'Under review',
        branch: 'FL',
        dateTime: '2024-08-10 04:00 PM',
    },
    {
        id: 'TXN12350',
        account: 'JamesWilson303',
        amount: '$1,500.00',
        comment: 'Pending withdrawal',
        adminComment: 'Pending',
        branch: 'WA',
        dateTime: '2024-08-10 05:15 PM',
    },
    {
        id: 'TXN12351',
        account: 'OliviaMartin404',
        amount: '$2,250.00',
        comment: 'Approved for withdrawal',
        adminComment: 'Completed',
        branch: 'NV',
        dateTime: '2024-08-10 06:30 PM',
    },
    {
        id: 'TXN12352',
        account: 'LiamHarris505',
        amount: '$1,800.00',
        comment: 'Pending withdrawal',
        adminComment: 'Under review',
        branch: 'NJ',
        dateTime: '2024-08-10 07:00 PM',
    },
    {
        id: 'TXN12353',
        account: 'EmmaClark606',
        amount: '$2,500.00',
        comment: 'Withdrawal requested',
        adminComment: 'Pending approval',
        branch: 'CO',
        dateTime: '2024-08-10 08:15 PM',
    },
    {
        id: 'TXN12354',
        account: 'NoahWright707',
        amount: '$950.00',
        comment: 'Pending processing',
        adminComment: 'Awaiting verification',
        branch: 'IL',
        dateTime: '2024-08-10 09:30 PM',
    },
];


export const depositData = [
    {
        id: 'DEP12345',
        account: 'MarkTaylor789',
        amount: '$2,000.00',
        comment: 'Pending deposit',
        adminComment: 'Awaiting confirmation',
        branch: 'TX',
        dateTime: '2024-08-10 10:00 AM',
    },
    {
        id: 'DEP12346',
        account: 'LisaWhite234',
        amount: '$1,500.00',
        comment: 'Deposit under review',
        adminComment: 'Review in progress',
        branch: 'CA',
        dateTime: '2024-08-10 11:30 AM',
    },
    {
        id: 'DEP12347',
        account: 'PaulJones345',
        amount: '$750.00',
        comment: 'Pending deposit approval',
        adminComment: 'Pending verification',
        branch: 'NY',
        dateTime: '2024-08-10 01:00 PM',
    },
    {
        id: 'DEP12348',
        account: 'AnnaDavis456',
        amount: '$3,200.00',
        comment: 'Deposit pending processing',
        adminComment: 'Processing initiated',
        branch: 'FL',
        dateTime: '2024-08-10 02:30 PM',
    },
    {
        id: 'DEP12349',
        account: 'RobertMartin567',
        amount: '$1,000.00',
        comment: 'Deposit awaiting action',
        adminComment: 'Action required',
        branch: 'WA',
        dateTime: '2024-08-10 04:00 PM',
    },
    {
        id: 'DEP12350',
        account: 'SophiaMiller678',
        amount: '$2,300.00',
        comment: 'Deposit requested',
        adminComment: 'Awaiting approval',
        branch: 'OR',
        dateTime: '2024-08-10 05:30 PM',
    },
    {
        id: 'DEP12351',
        account: 'EthanRodriguez789',
        amount: '$850.00',
        comment: 'Pending verification',
        adminComment: 'Verification in progress',
        branch: 'GA',
        dateTime: '2024-08-10 06:45 PM',
    },
    {
        id: 'DEP12352',
        account: 'AvaWilson890',
        amount: '$1,400.00',
        comment: 'Deposit under review',
        adminComment: 'Review initiated',
        branch: 'MI',
        dateTime: '2024-08-10 08:00 PM',
    },
    {
        id: 'DEP12353',
        account: 'OliverLopez901',
        amount: '$950.00',
        comment: 'Deposit awaiting action',
        adminComment: 'Action required',
        branch: 'VA',
        dateTime: '2024-08-10 09:15 PM',
    },
    {
        id: 'DEP12354',
        account: 'IsabellaGonzalez012',
        amount: '$2,700.00',
        comment: 'Pending deposit',
        adminComment: 'Awaiting confirmation',
        branch: 'NC',
        dateTime: '2024-08-10 10:30 PM',
    },
];


export const loanData = [
    {
        id: 'LOAN12345',
        account: 'SophiaJohnson678',
        amount: '$10,000.00',
        comment: 'Pending loan approval',
        adminComment: 'Documentation required',
        branch: 'GA',
        dateTime: '2024-08-10 09:00 AM',
    },
    {
        id: 'LOAN12346',
        account: 'JacksonSmith789',
        amount: '$5,000.00',
        comment: 'Loan under review',
        adminComment: 'Review in process',
        branch: 'NV',
        dateTime: '2024-08-10 10:30 AM',
    },
    {
        id: 'LOAN12347',
        account: 'EmilyBrown890',
        amount: '$8,500.00',
        comment: 'Pending loan disbursement',
        adminComment: 'Awaiting final approval',
        branch: 'TX',
        dateTime: '2024-08-10 12:00 PM',
    },
    {
        id: 'LOAN12348',
        account: 'JamesWilliams901',
        amount: '$12,000.00',
        comment: 'Loan application under review',
        adminComment: 'In review stage',
        branch: 'CA',
        dateTime: '2024-08-10 01:30 PM',
    },
    {
        id: 'LOAN12349',
        account: 'OliviaTaylor012',
        amount: '$7,200.00',
        comment: 'Pending loan approval',
        adminComment: 'Awaiting approval',
        branch: 'FL',
        dateTime: '2024-08-10 03:00 PM',
    },
    {
        id: 'LOAN12350',
        account: 'LiamMartin123',
        amount: '$9,000.00',
        comment: 'Pending documentation',
        adminComment: 'Waiting for documents',
        branch: 'NY',
        dateTime: '2024-08-10 04:30 PM',
    },
    {
        id: 'LOAN12351',
        account: 'MiaGarcia234',
        amount: '$6,500.00',
        comment: 'Loan under assessment',
        adminComment: 'Assessment in progress',
        branch: 'OH',
        dateTime: '2024-08-10 06:00 PM',
    },
    {
        id: 'LOAN12352',
        account: 'NoahHarris345',
        amount: '$11,500.00',
        comment: 'Pending loan approval',
        adminComment: 'Pending review',
        branch: 'PA',
        dateTime: '2024-08-10 07:30 PM',
    },
    {
        id: 'LOAN12353',
        account: 'AvaRodriguez456',
        amount: '$4,500.00',
        comment: 'Loan application under review',
        adminComment: 'Documents submitted',
        branch: 'IL',
        dateTime: '2024-08-10 09:00 PM',
    },
    {
        id: 'LOAN12354',
        account: 'EthanYoung567',
        amount: '$8,000.00',
        comment: 'Pending final approval',
        adminComment: 'Final review pending',
        branch: 'MI',
        dateTime: '2024-08-10 10:30 PM',
    },
];


export const buttons = [
    {
        label: 'Approve',
        className: 'bg-green-500 hover:bg-green-600 text-white font-semibold py-2 px-4 rounded',
        onClick: (row) => console.log('Approved:', row),
    },
    {
        label: 'Hold',
        className: 'bg-yellow-500 hover:bg-yellow-600 text-white font-semibold py-2 px-4 rounded',
        onClick: (row) => console.log('On Hold:', row),
    },
    {
        label: 'Reject',
        className: 'bg-red-500 hover:bg-red-600 text-white font-semibold py-2 px-4 rounded',
        onClick: (row) => console.log('Rejected:', row),
    },
];


// Manual Acceptance 
export const manualAcceptanceData = [
    {
        id: 1,
        account: "AC12345",
        datetime: "2024-08-01 12:30:00",
        script: "AAPL",
        type: "Buy",
        type_detail: "Market",
        amount_at_price: 150.00,
        acceptance_amount: 1500.00,
        acceptance_price: 150.00,
        mode: "Value",
        method: "Online",
        open_position: 10,
        commission: 15.00,
        profit: 100.00,
    },
    {
        id: 2,
        account: "AC67890",
        datetime: "2024-08-02 14:45:00",
        script: "TSLA",
        type: "Sell",
        type_detail: "Limit",
        amount_at_price: 650.00,
        acceptance_amount: 6500.00,
        acceptance_price: 650.00,
        mode: "Markup",
        method: "Manual",
        open_position: 5,
        commission: 30.00,
        profit: -50.00,
    },
    {
        id: 3,
        account: "AC54321",
        datetime: "2024-08-03 09:15:00",
        script: "GOOGL",
        type: "Buy",
        type_detail: "Stop-Loss",
        amount_at_price: 2750.00,
        acceptance_amount: 27500.00,
        acceptance_price: 2750.00,
        mode: "Value",
        method: "Online",
        open_position: 15,
        commission: 20.00,
        profit: 200.00,
    },
    {
        id: 4,
        account: "AC98765",
        datetime: "2024-08-04 16:00:00",
        script: "AMZN",
        type: "Sell",
        type_detail: "Market",
        amount_at_price: 3400.00,
        acceptance_amount: 34000.00,
        acceptance_price: 3400.00,
        mode: "Markup",
        method: "Manual",
        open_position: 8,
        commission: 25.00,
        profit: -100.00,
    },
    {
        id: 5,
        account: "AC11223",
        datetime: "2024-08-05 11:20:00",
        script: "MSFT",
        type: "Buy",
        type_detail: "Limit",
        amount_at_price: 280.00,
        acceptance_amount: 2800.00,
        acceptance_price: 280.00,
        mode: "Value",
        method: "Online",
        open_position: 12,
        commission: 18.00,
        profit: 150.00,
    },
    {
        id: 6,
        account: "AC33445",
        datetime: "2024-08-06 13:30:00",
        script: "NFLX",
        type: "Sell",
        type_detail: "Stop-Loss",
        amount_at_price: 500.00,
        acceptance_amount: 5000.00,
        acceptance_price: 500.00,
        mode: "Markup",
        method: "Manual",
        open_position: 7,
        commission: 22.00,
        profit: -75.00,
    },
    {
        id: 7,
        account: "AC55667",
        datetime: "2024-08-07 15:00:00",
        script: "FB",
        type: "Buy",
        type_detail: "Market",
        amount_at_price: 325.00,
        acceptance_amount: 3250.00,
        acceptance_price: 325.00,
        mode: "Value",
        method: "Online",
        open_position: 9,
        commission: 12.00,
        profit: 90.00,
    },
    {
        id: 8,
        account: "AC77889",
        datetime: "2024-08-08 17:10:00",
        script: "NVDA",
        type: "Sell",
        type_detail: "Limit",
        amount_at_price: 700.00,
        acceptance_amount: 7000.00,
        acceptance_price: 700.00,
        mode: "Markup",
        method: "Manual",
        open_position: 6,
        commission: 28.00,
        profit: -120.00,
    },
    {
        id: 9,
        account: "AC99000",
        datetime: "2024-08-09 10:25:00",
        script: "INTC",
        type: "Buy",
        type_detail: "Stop-Loss",
        amount_at_price: 150.00,
        acceptance_amount: 1500.00,
        acceptance_price: 150.00,
        mode: "Value",
        method: "Online",
        open_position: 20,
        commission: 10.00,
        profit: 75.00,
    },
    {
        id: 10,
        account: "AC10101",
        datetime: "2024-08-10 12:45:00",
        script: "AMD",
        type: "Sell",
        type_detail: "Market",
        amount_at_price: 450.00,
        acceptance_amount: 4500.00,
        acceptance_price: 450.00,
        mode: "Markup",
        method: "Manual",
        open_position: 11,
        commission: 20.00,
        profit: -60.00,
    },
];



export const manualAcceptancecolumns = [
    { header: 'ID', accessor: 'id' },
    { header: 'Account', accessor: 'account' },
    { header: 'Date/Time', accessor: 'datetime' },
    { header: 'Script', accessor: 'script' },
    { header: 'Type', accessor: 'type' },
    { header: 'Type Detail', accessor: 'type_detail' },
    { header: 'Amount @ Price', accessor: 'amount_at_price' },
    { header: 'Acceptance Amount', accessor: 'acceptance_amount' },
    { header: 'Acceptance Price', accessor: 'acceptance_price' },
    { header: 'Mode (Value/Markup)', accessor: 'mode' },
    { header: 'Method', accessor: 'method' },
    { header: 'Open Position', accessor: 'open_position' },
    { header: 'Commission', accessor: 'commission' },
    { header: 'Profit', accessor: 'profit' },
    { header: 'Action', accessor: 'action' },
];

export const manualAcceptancebuttons = [
    {
        label: 'Accept',
        className: 'bg-green-500 hover:bg-green-600 text-white font-semibold py-2 px-4 rounded',
        onClick: (row) => console.log('Approved:', row),
    },
    {
        label: 'Reject',
        className: 'bg-red-500 hover:bg-red-600 text-white font-semibold py-2 px-4 rounded',
        onClick: (row) => console.log('Rejected:', row),
    },
];