export const loanRequestData = [
  {
    id: 'L001',
    amount: 5000,
    status: 'Pending',
    comment: 'Request for new business loan',
    admin_comment: 'Pending approval from credit department',
    branch: 'Main Branch',
    'date/Time': '2024-08-10 08:30:00',
  },
  {
    id: 'L002',
    amount: 15000,
    status: 'Approved',
    comment: 'Loan for expansion of business',
    admin_comment: 'Approved and funds disbursed',
    branch: 'Downtown Branch',
    'date/Time': '2024-08-10 09:00:00',
  },
  {
    id: 'L003',
    amount: 7500,
    status: 'Rejected',
    comment: 'Insufficient credit score',
    admin_comment: 'Rejected due to low credit score',
    branch: 'Suburban Branch',
    'date/Time': '2024-08-10 10:15:00',
  },
  {
    id: 'L004',
    amount: 2000,
    status: 'Pending',
    comment: 'Personal loan request',
    admin_comment: 'Under review for documentation',
    branch: 'City Branch',
    'date/Time': '2024-08-10 11:30:00',
  },
  {
    id: 'L005',
    amount: 10000,
    status: 'Approved',
    comment: 'Loan for equipment purchase',
    admin_comment: 'Approved and processing',
    branch: 'Business Branch',
    'date/Time': '2024-08-10 13:00:00',
  },
  {
    id: 'L006',
    amount: 3000,
    status: 'Pending',
    comment: 'Loan for personal use',
    admin_comment: 'Awaiting further information',
    branch: 'North Branch',
    'date/Time': '2024-08-10 14:00:00',
  },
  {
    id: 'L007',
    amount: 12000,
    status: 'Approved',
    comment: 'Loan for home renovation',
    admin_comment: 'Approved and ready for disbursement',
    branch: 'South Branch',
    'date/Time': '2024-08-10 15:00:00',
  },
  {
    id: 'L008',
    amount: 5000,
    status: 'Rejected',
    comment: 'Loan rejected due to high risk',
    admin_comment: 'Rejected due to risk assessment',
    branch: 'East Branch',
    'date/Time': '2024-08-10 16:00:00',
  },
  {
    id: 'L009',
    amount: 8000,
    status: 'Pending',
    comment: 'Loan for vehicle purchase',
    admin_comment: 'Undergoing approval process',
    branch: 'West Branch',
    'date/Time': '2024-08-10 17:00:00',
  },
  {
    id: 'L010',
    amount: 2200,
    status: 'Approved',
    comment: 'Loan for education expenses',
    admin_comment: 'Approved and disbursed',
    branch: 'Central Branch',
    'date/Time': '2024-08-10 18:00:00',
  },
  {
    id: 'L011',
    amount: 1000,
    status: 'Rejected',
    comment: 'Loan amount below minimum threshold',
    admin_comment: 'Rejected due to policy constraints',
    branch: 'Branch A',
    'date/Time': '2024-08-10 19:00:00',
  },
];
