export const esouqmanagerData= [
    {
      name: "Gold Necklace",
      description: "Elegant 18K gold necklace with intricate design.",
      script: "AU999",
      code: "GN001",
      weight: "25g",
      vat: "10%",
      "premium/discount": "Premium 5%",
      deliveryCharges: "$20",
      makingCharges: "$100",
      availableCharges: "$50",
      ImageUrl: "https://example.com/images/gold_necklace.jpg",
      enabled: "true",
    },
    {
      name: "Silver Bracelet",
      description: "Sterling silver bracelet with a sleek finish.",
      script: "AG925",
      code: "SB002",
      weight: "15g",
      vat: "8%",
      "premium/discount": "Discount 3%",
      deliveryCharges: "$15",
      makingCharges: "$50",
      availableCharges: "$25",
      ImageUrl: "https://example.com/images/silver_bracelet.jpg",
      enabled: "false",
    },
    {
      name: "Platinum Ring",
      description: "Platinum ring with a solitaire diamond setting.",
      script: "PT950",
      code: "PR003",
      weight: "10g",
      vat: "12%",
      "premium/discount": "Premium 7%",
      deliveryCharges: "$25",
      makingCharges: "$150",
      availableCharges: "$75",
      ImageUrl: "https://example.com/images/platinum_ring.jpg",
      enabled: "true",
    },
    {
      name: "Diamond Earrings",
      description: "Stunning diamond earrings with white gold setting.",
      script: "AU750",
      code: "DE004",
      weight: "8g",
      vat: "10%",
      "premium/discount": "Premium 6%",
      deliveryCharges: "$18",
      makingCharges: "$120",
      availableCharges: "$60",
      ImageUrl: "https://example.com/images/diamond_earrings.jpg",
      enabled: "true",
    },
    {
      name: "Gold Bangle",
      description: "24K gold bangle with traditional motifs.",
      script: "AU999",
      code: "GB005",
      weight: "30g",
      vat: "10%",
      "premium/discount": "Premium 4%",
      deliveryCharges: "$22",
      makingCharges: "$80",
      availableCharges: "$40",
      ImageUrl: "https://example.com/images/gold_bangle.jpg",
      enabled: "false",
    },
  ];
  